# Generated by Django 4.2.6 on 2023-10-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumaccount',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ethereumaccount',
            name='private_key',
            field=models.CharField(max_length=100),
        ),
    ]
